### ISSUE TITLE
rest of Mastodon's unofficial extension properties

### ISSUE THREAD

**Issue by snarfed** [swicg/miscellany#7]
TODO: expand https://docs.joinmastodon.org/spec/activitypub/#extensions-not-defined-by-activitystreams into an issue per property. List:

* `featured`
* `featuredTags`
* `discoverable`
* `indexable (not listed on their docs page)`
* `suspended`
* `focalPoint`
* `blurhash`
* `as:sensitive`

...and non-standard object types, eg in `tag` and `attachments`:
* `PropertyValue`
* `IdentityProof`
* `Hashtag`
* `Emoji`

**Comment by evanp** [comment]
I'm -1 on this.

So, I'd really like to keep this miscellany project constrained to widely-used terms in the AS2 namespace that aren't in the AS2 context document yet.

I think it's up to Mastodon to document stuff in their own namespace ("toot:" prefix). And if they want to make it part of the AS2 context document, they can submit them.

In general, we're trying to catch the existing terms in the AS2 namespace, so new extensions are in their own namespaces.

**Comment by evanp** [comment]
That said, I'll look through the Mastodon docs and see if there are terms in the AS2 namespace that would be good candidates here.

**Comment by snarfed** [comment]
Sure! I didn't fully understand the goals here, but I do now (more, at least), and that makes sense.

**Comment by evanp** [comment]
I also added an issue for the extension policy on this situation. swicg/extension-policy#18

**Comment by evanp** [comment]
@snarfed I'm going to close this if you're OK with it.
